#set -g status off
set-option -g status-position top
set-option -g status-right ""
set -g status-justify centre
set -g window-status-activity-bg red
set-option -g window-status-activity-bg red
set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh
set-option -g status-justify centre
set -g mouse on
